# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-07-23 23:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('image', 'Image'), ('document', 'Document'), ('audio', 'Audio'), ('video', 'Video')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='imagedetail',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.ProxyAsset'),
        ),
    ]
